### ISSUE TITLE
flex becomes flex="flex" which breaks in Angular Material for Meteor

### ISSUE THREAD

**Issue by mattiLeBlanc** [civilframe/meteor-angular-jade#11]
Hi,

I am working on an angular+meteor project using the package civilframe:angular-jade to enable ng.jade templates.
This package is using this Jade package for compiling.
Anyway, I noticed that when ng.jade is converted it tends to change the single attributes without value.

div(flex) Foo
becomes

<div flex="flex">Foo</div>
It should just stay

<div flex>Foo</div>
because Angular Materials is tripping over this. It doesn't know flex="flex" and turns into class="flex-flex" :)

Is there an easy fix to not convert attributes that are without value?

**Comment by pbastowski** [comment]
@mattiLeBlanc yes, this is a known issue and the workaround is to do this `div(flex="") Foo`.

It is possible to implement a global change to this repo to support the what you're asking, but it would affect those people who depend on the current functionality.

The jade compiler itself has an option `{ doctype: 'html' }`, which when combined with this line at the top of your code `doctype html`, results in what you're after. But, as I said, some people depend on the current functionality.

@civilframe what are your thoughts on this topic?

I'm thinking angular jade partials/templates never have `doctype html`at the top of the file. So, I could prepend that to each file and add the option `{ doctype: 'html' }` to the compiler options. Then, I would need to remove the first line `<!DOCTYPE html>` from the generated HTML. It's certainly doable, I'm just not sure we should do it.

**Comment by mattiLeBlanc** [comment]
It wasn't and issue before angular Material 0.11.12, but I see angular is already at version 0.11.14 and they said they where going to support `flex="flex"`.
So maybe you don't have to do anything?

**Comment by pbastowski** [comment]
So, are ok with my above suggestion to explicitly use the `flex=""` syntax?

If so, then can we close the issue?

**Comment by civilframe** [comment]
The jade compiler does this by default, so I would just do flex="".

**Comment by mattiLeBlanc** [comment]
yes I concur.
