### ISSUE TITLE
compile .jade to .html, but with JavaScript code inside

### ISSUE THREAD

**Issue by ericwangqing** [civilframe/meteor-angular-jade#12]
I am trying to use jade instead of html in the tutorial of http://info.meteor.com/blog/whatsapp-with-meteor-angular-and-ionic, but it didn't work. I found that unlike a *.html template which had been compiled to  a *.html.js file, a *.jade temlplate been compiled to a  *.html file but with JavaScript inside.

**Comment by pbastowski** [comment]
This is not a bug or an issue. It is a feature of this package.

Just in case you didn't know:

- When you use this package your JADE files must have the `.ng.jade` extension. Did you do that?

- Then, once compiled by JADE, in your AngularJS code you will be able to refer to each file by its name, but with a `.html` extension. For example `client/myfile.ng.jade` becomes `client/myfile.html`.

Is there any specific reason you are expecting the extensions to be `.html.js`?
