### ISSUE TITLE
Not working with Meteor 1.3+

### ISSUE THREAD

**Issue by mackbrowne** [civilframe/meteor-angular-jade#15]
I'm trying to get the socially angular 1 example working with this plugin.  Perhaps with the new changes to angular1-meteor with the addition of typescript and npm, could something have gone wrong?  Can anyone confirm if this plugin is working for them with the current version of angular-meteor?

**Comment by mattiLeBlanc** [comment]
It is working for me, angular 1.5. What issues are you running into?
Do you name your files 'file.ng.jade'? And if you use ui-router, to you just reference the template as 'file.html'?

**Comment by mackbrowne** [comment]
Hello,

Yes I'm naming them ng.html.  I'll try converting to jade and naming them
with  .html? Is that what you are suggesting?

**Comment by mattiLeBlanc** [comment]
if you want to use Jade, you should name them template.ng.jade.
Maybe I didn't understand your question?

**Comment by mackbrowne** [comment]
No no, I didn't understand your response I got it now.   I was naming
things with. Ng.html not template.ng.html.   Will try that and get back to
you

**Comment by mattiLeBlanc** [comment]
uh,wait. Do not use template as a filename.Just read it as [templateName].ng.jade.
Like userList.ng.jade, or checkout.ng.jade.

**Comment by mackbrowne** [comment]
Will try and let you know

**Comment by mackbrowne** [comment]
Im attempting to add

`meteor add civilframe:angular-jade`

to this project - https://github.com/mackbrowne/meteor-angular-boilerplate

then I try converting a single file to jade formatting and renaming to .ng.jade, .jade, .ng.html, .html and any other combinations I thought would make sense.  Nothing seems to work.

**Comment by civilframe** [comment]
@mackbrowne Please create a branch in your project where the package is not working, and I can take a look.

**Comment by mackbrowne** [comment]
[Here](https://github.com/mackbrowne/meteor-angular-boilerplate/tree/jade) is the fork of socially with 1 file changed to jade.

the file i converted to jade is found [here](https://github.com/mackbrowne/meteor-angular-boilerplate/tree/jade/imports/ui/components/partiesList)

**Comment by mackbrowne** [comment]
@civilframe got any time to look at this?  I setup the branch you asked for.

Vanilla html is soo ugly!!

**Comment by civilframe** [comment]
@mackbrowne Meteor made some changes starting in version 1.3 that breaks the plugin. For now, the plugin will only work with Meteor 1.2 and earlier. Also, note that the plugin adds the jade files to the angular $templateCache - it doesn't actually put compiled jade files into your project structure, for you to import them. You would use templateUrl instead.

**Comment by pbastowski** [comment]
@mackbrowne 
I have created a package `pbastowski:jade-templates`, which is built for Meteor 1.3 and up. It does not put templates in the template cache and instead let's you import them as text that you can use with `template`. Check it out, as It may be suitable for your needs.

**Comment by mackbrowne** [comment]
@civilframe lol i just saw that you updated the documentation.  The next person coming across this issue will really appreciate it.

@pbastowski not sure what I'd do without you this week.  Thank you again and again.

**Comment by civilframe** [comment]
Thanks @pbastowski . For everyone stumbling on this issue, let me recommend using `pbastowski:jade-templates`.

**Comment by mattiLeBlanc** [comment]
Would this work the same for PUG?

**Comment by pbastowski** [comment]
@mattiLeBlanc 
The answer is no, because PUG is just JADE under a new name, due to copyright issues.

**Comment by mattiLeBlanc** [comment]
Yes, I assumed so. Just putting it out their for the people that might have had this question :)
