### ISSUE TITLE
Using Jade template with Angular-meteor, display issue

### ISSUE THREAD

**Issue by mattiLeBlanc** [civilframe/meteor-angular-jade#5]
```
(function(){angular.module('angular-meteor').run(['$templateCache', function($templateCache) {$templateCache.put('client/index2.html', '
JADE Nothing here

');}]); })();
```

This is what I get when I reference a 'sometemplate.ng.jade' as sometemplate.html as suggested.

Code
```
import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
  selector: 'app'
})
@View({
  // template: "<p>Hello World!2</p>"
  templateUrl: 'client/index2.html'
})
class Socially {}

bootstrap(Socially);
```

index2.ng.jade file:
```
p JADE Nothing here
```

*Edit:
So far I can see that the results string you create and feed to the compileStep.addJavascript function is just literally printed and not executed.

**Comment by pbastowski** [comment]
What you are doing "wrong" is you're using actual Angular2. This JADE package works with Angular1. 

If you want Angular2-ish syntax then try the `angular2-now` library.

**Comment by mattiLeBlanc** [comment]
That's quick. Thanks.
Okay, I didn't realise it was for Angular 1 only.
I will look at angular2-now, thanks!

**Comment by civilframe** [comment]
@mattiLeBlanc I will make a new issue for that request: https://github.com/civilframe/meteor-angular-jade/issues/6

Thanks!
