### ISSUE TITLE
New branch with ability to also create normal HTML templates like index.ng.jade

### ISSUE THREAD

**Issue by pbastowski** [civilframe/meteor-angular-jade#9]
Some users, including myself, would like to be able to use this package to do all our JADE to HTML conversions, including `index.ng.jade`. Currently, this package outputs only JS files that populate the Angular `$templateCache`. So, I decided to enhance it a bit...

The changes I made in this version
https://github.com/pbastowski/meteor-angular-jade/tree/feature/templateCacheOff
allow this package to also output HTML code, which means that we can now also use it for `index.ng.jade` :)

To create normal HTML files just add the comment shown below as the first line in your JADE file and the plugin will create an HTML output file, instead of putting the HTML code in the Angular `$templateCache`.

```jade
// templateCache off
p The rest of your JADE code
```
> Please note, this is only an early version and I have only done a bit of testing with this today on a couple of projects of mine. 

It appears to work, but I don't feel confident yet that enough testing has been done to conclude that this mod is ready to be released to the public. I would like some people ( also looking at you @civilframe ), to test this for us and hopefully find any bugs and either fix them or report them to us for fixing.

I haven't made a pull request for this change, because I don't know how to make a PR that also creates a new branch and I don't want this in `master` until it's ready.

**Comment by pbastowski** [comment]
I just found a bug while trying this in one of my other projects... can't work on it right now, unfortunately. The problem is that the body section of index.html must be created as some kind of a special template and right now it is not being done that way and so in this particular project the index page's body does not load up....

to be continued...

**Comment by mattiLeBlanc** [comment]
Why would you want to have a index.ng.jade? I am having a index.jade in my Meteor + Angular project which is nothing more then the wrapper of the first ui-view.
I wonder what your motivation is?

**Comment by pbastowski** [comment]
@mattiLeBlanc Why? Because it can be done and below is a sample index.jade:

```jade
// templateCache off
head
  meta(name='viewport', content='width=device-width, initial-scale=1')
  base(href='/')
  link(href='https://fonts.googleapis.com/icon?family=Material+Icons', rel='stylesheet')
  
body(layout='column')
  
  socially
```

In answer to your second question about the motivation, I have thought about this overnight and I agree with you. There is too little to gain in this mod to put any more effort into it. But, it was a fun thing to try and do :) Even if the problems it solves doesn't, for the most part, exist.

So, I'm closing this "issue".

**Comment by mattiLeBlanc** [comment]
okay fair enough :). 

This is my index.jade:
```
head
  meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no")
  base(href="/")

body(layout="column")
  div(ui-view="app" layout="column" flex)
```

Works like a charm
